# Generated by Django 5.2.7 on 2026-09-18 00:05

import django.db.models.deletion
import seals.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Seal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero_serial', models.CharField(default=seals.models.generate_serial, editable=False, max_length=24, unique=True)),
                ('token_publico', models.CharField(default=seals.models.generate_public_token, editable=False, max_length=64, unique=True)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('ATIVO', 'Ativo'), ('BLOQUEADO', 'Bloqueado'), ('CANCELADO', 'Cancelado'), ('EXPIRADO', 'Expirado')], default='PENDENTE', max_length=20)),
                ('validade', models.DateField(blank=True, null=True)),
                ('emitido_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('emitido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selos_emitidos', to=settings.AUTH_USER_MODEL)),
                ('veiculo', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='selo', to='vehicles.vehicle')),
            ],
            options={
                'verbose_name': 'selo',
                'verbose_name_plural': 'selos',
                'ordering': ('-emitido_em',),
            },
        ),
        migrations.CreateModel(
            name='SealRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacao_usuario', models.TextField(blank=True, verbose_name='observação')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('APROVADA', 'Aprovada'), ('REJEITADA', 'Rejeitada')], default='PENDENTE', max_length=20)),
                ('solicitado_em', models.DateTimeField(auto_now_add=True)),
                ('analisado_em', models.DateTimeField(blank=True, null=True)),
                ('analisado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitacoes_analisadas', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitacoes_selo', to=settings.AUTH_USER_MODEL)),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitacoes_selo', to='vehicles.vehicle')),
            ],
            options={
                'verbose_name': 'solicitação de selo',
                'verbose_name_plural': 'solicitações de selo',
                'ordering': ('-solicitado_em',),
            },
        ),
        migrations.CreateModel(
            name='SealScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consultado_em', models.DateTimeField(auto_now_add=True)),
                ('endereco_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('agente_usuario', models.CharField(blank=True, max_length=250)),
                ('selo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultas', to='seals.seal')),
            ],
            options={
                'verbose_name': 'consulta de selo',
                'verbose_name_plural': 'consultas de selos',
                'ordering': ('-consultado_em',),
            },
        ),
    ]
