# Generated by Django 5.2.7 on 2026-09-18 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_ramal'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'conta de acesso', 'verbose_name_plural': 'contas de acesso'},
        ),
    ]
