# Generated by Django 5.2.7 on 2026-09-18 00:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=30, verbose_name='número da CNH')),
                ('categoria', models.CharField(max_length=5)),
                ('validade', models.DateField()),
                ('arquivo', models.FileField(upload_to='documentos/cnh/%Y/%m/')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('VERIFICADO', 'Verificado'), ('REJEITADO', 'Rejeitado'), ('VENCIDO', 'Vencido')], default='PENDENTE', max_length=20)),
                ('motivo_status', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cnhs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'CNH',
                'verbose_name_plural': 'CNHs',
                'ordering': ('-criado_em',),
            },
        ),
        migrations.CreateModel(
            name='VehicleDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercicio', models.PositiveSmallIntegerField(verbose_name='ano do licenciamento — exercício do CRLV')),
                ('arquivo', models.FileField(upload_to='documentos/crlv/%Y/%m/')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('VERIFICADO', 'Verificado'), ('REJEITADO', 'Rejeitado'), ('VENCIDO', 'Vencido')], default='PENDENTE', max_length=20)),
                ('motivo_status', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='crlvs', to='vehicles.vehicle')),
            ],
            options={
                'verbose_name': 'CRLV',
                'verbose_name_plural': 'CRLVs',
                'ordering': ('-exercicio', '-criado_em'),
                'constraints': [models.UniqueConstraint(fields=('veiculo', 'exercicio'), name='unique_crlv_vehicle_year')],
            },
        ),
    ]
