# Generated by Django 5.2.7 on 2026-09-18 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverdocument',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cnhs', to='people.person'),
        ),
    ]
