# Generated by Django 5.2.7 on 2026-09-18 13:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def copy_people(apps, schema_editor):
    User = apps.get_model('accounts', 'User')
    Person = apps.get_model('people', 'Person')
    db = schema_editor.connection.alias
    related = set()
    for app, model, field in [('vehicles', 'Vehicle', 'proprietario_id'), ('documents', 'DriverDocument', 'usuario_id'), ('operations', 'Occurrence', 'proprietario_id'), ('seals', 'SealRequest', 'usuario_id')]:
        related.update(apps.get_model(app, model).objects.using(db).values_list(field, flat=True))
    fields = ('username', 'first_name', 'last_name', 'nome_preferido', 'email', 'cpf', 'vinculo', 'classe_funcional', 'cargo', 'identidade_funcional', 'organizacao', 'secao', 'telefone', 'ramal', 'is_active', 'cadastro_aprovado')
    for user in User.objects.using(db).all().iterator():
        administrator = user.is_superuser or user.role == 'ADMINISTRADOR'
        if not administrator or user.pk in related:
            Person.objects.using(db).create(pk=user.pk, legacy_user_id=user.pk, **{field: getattr(user, field) for field in fields})
        if not administrator:
            User.objects.using(db).filter(pk=user.pk).update(is_active=False)


def restore_access(apps, schema_editor):
    User = apps.get_model('accounts', 'User')
    Person = apps.get_model('people', 'Person')
    db = schema_editor.connection.alias
    for person in Person.objects.using(db).exclude(legacy_user_id=None).iterator():
        User.objects.using(db).filter(pk=person.legacy_user_id).update(is_active=person.is_active)


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0002_user_ramal'),
        ('vehicles', '0001_initial'),
        ('documents', '0001_initial'),
        ('seals', '0001_initial'),
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompletionImport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('payload', models.JSONField(default=list)),
                ('replace_existing', models.BooleanField(default=False)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('username', models.CharField(default=uuid.uuid4, editable=False, max_length=150, unique=True, verbose_name='referência da importação')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='nome')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='sobrenome')),
                ('nome_preferido', models.CharField(blank=True, max_length=80, verbose_name='nome preferido')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='e-mail')),
                ('cpf', models.CharField(blank=True, max_length=11, null=True, unique=True, verbose_name='CPF')),
                ('vinculo', models.CharField(choices=[('COLABORADOR', 'Colaborador'), ('PRESTADOR', 'Prestador'), ('OUTRO', 'Outro')], default='COLABORADOR', max_length=20, verbose_name='vínculo')),
                ('classe_funcional', models.CharField(choices=[('GRUPO_A', 'GRUPO A'), ('GRUPO_B', 'GRUPO B'), ('GRUPO_C', 'Grupo C'), ('PRESTADOR', 'Prestador'), ('SEM_CLASSE', 'Não informada')], default='SEM_CLASSE', max_length=20, verbose_name='categoria')),
                ('cargo', models.CharField(blank=True, max_length=60, verbose_name='cargo')),
                ('identidade_funcional', models.CharField(blank=True, max_length=30, verbose_name='identidade funcional')),
                ('organizacao', models.CharField(blank=True, max_length=120, verbose_name='organização')),
                ('secao', models.CharField(blank=True, max_length=120, verbose_name='seção / setor')),
                ('telefone', models.CharField(blank=True, max_length=30, verbose_name='telefone')),
                ('ramal', models.CharField(blank=True, max_length=30, verbose_name='ramal')),
                ('is_active', models.BooleanField(default=True, verbose_name='cadastro ativo')),
                ('cadastro_aprovado', models.BooleanField(default=False)),
                ('review_status', models.CharField(choices=[('PENDING', 'Aguardando conferência'), ('VERIFIED', 'Conferido')], default='PENDING', max_length=12, verbose_name='conferência')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('legacy_user', models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='person_record', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'pessoa',
                'verbose_name_plural': 'pessoas',
                'ordering': ('nome_preferido', 'first_name', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='PersonChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('at', models.DateTimeField(auto_now_add=True)),
                ('source', models.CharField(max_length=200, verbose_name='origem')),
                ('changes', models.JSONField(default=dict)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='changes', to='people.person')),
            ],
            options={
                'verbose_name': 'alteração de cadastro',
                'verbose_name_plural': 'histórico dos cadastros',
                'ordering': ('-at', '-pk'),
            },
        ),
        migrations.RunPython(copy_people, restore_access),
    ]
