# Generated by Django 5.2.7 on 2026-09-18 00:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=7, unique=True)),
                ('renavam', models.CharField(max_length=11, unique=True)),
                ('chassi', models.CharField(blank=True, max_length=17)),
                ('tipo', models.CharField(choices=[('CARRO', 'Carro'), ('MOTO', 'Motocicleta'), ('CAMINHONETE', 'Caminhonete'), ('OUTRO', 'Outro')], default='CARRO', max_length=20)),
                ('marca', models.CharField(max_length=60)),
                ('modelo', models.CharField(max_length=80)),
                ('cor', models.CharField(max_length=40)),
                ('ano_fabricacao', models.PositiveSmallIntegerField(verbose_name='ano de fabricação')),
                ('ano_modelo', models.PositiveSmallIntegerField(verbose_name='ano do modelo')),
                ('foto_dianteira', models.ImageField(blank=True, upload_to='veiculos/%Y/%m/')),
                ('foto_traseira', models.ImageField(blank=True, upload_to='veiculos/%Y/%m/')),
                ('status', models.CharField(choices=[('EM_ANALISE', 'Em análise'), ('APROVADO', 'Aprovado'), ('REJEITADO', 'Rejeitado'), ('INATIVO', 'Inativo')], default='EM_ANALISE', max_length=20)),
                ('motivo_status', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('proprietario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='veiculos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'veículo',
                'verbose_name_plural': 'veículos',
                'ordering': ('placa',),
            },
        ),
    ]
