# Generated by Django 5.2.7 on 2026-09-18 00:05

import django.db.models.deletion
import django.utils.timezone
import operations.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('seals', '0001_initial'),
        ('vehicles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Occurrence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(default=operations.models.generate_number, editable=False, max_length=24, unique=True)),
                ('tipo', models.CharField(choices=[('ABORDAGEM', 'Abordagem'), ('IRREGULARIDADE', 'Irregularidade'), ('ACIDENTE', 'Acidente'), ('FURTO_DUMBO', 'Furto / roubo'), ('SELO_DANIFICADO', 'Selo danificado'), ('SELO_IRREGULAR', 'Selo irregular'), ('DOCUMENTO', 'Problema documental'), ('OUTRO', 'Outro')], max_length=30)),
                ('status', models.CharField(choices=[('ABERTA', 'Aberta'), ('EM_ANALISE', 'Em análise'), ('ENCERRADA', 'Encerrada')], default='ABERTA', max_length=20)),
                ('data_hora', models.DateTimeField(default=django.utils.timezone.now, verbose_name='data e hora')),
                ('local', models.CharField(max_length=200)),
                ('descricao', models.TextField(verbose_name='descrição')),
                ('providencias', models.TextField(blank=True, verbose_name='providências')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('proprietario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ocorrencias', to=settings.AUTH_USER_MODEL)),
                ('registrado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ocorrencias_registradas', to=settings.AUTH_USER_MODEL)),
                ('selo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ocorrencias', to='seals.seal')),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ocorrencias', to='vehicles.vehicle')),
            ],
            options={
                'verbose_name': 'ocorrência',
                'verbose_name_plural': 'ocorrências',
                'ordering': ('-data_hora',),
            },
        ),
    ]
